### ISSUE TITLE
I can't add a new folder or new file

### ISSUE THREAD

**Issue by jescoboza** [mrpritchett/buddydrive#25]
When I'm in BuddyDrive on the front end, the New File button and the New Folder Button are not working. It will not let me add a new folder nor a new file. What can I do to fix this?

Joey

**Comment by imath** [comment]
Try with a default config : 
- WordPress 4.2
- BuddyPress 2.2.3.1
- BuddyDrive 1.2.3

twentyfifteen or twentytwelve WordPress theme

It can be many things :  a template trouble / css one / javascript one. So best is to always test in default to find what's going wrong with the theme you activated or one of the plugin you activated.

**Comment by mrpritchett** [comment]
Closing due to lack of reply.
