### ISSUE TITLE
Implement CMIS (allow BuddyDrive to be used like Dropbox)

### ISSUE THREAD

**Issue by nicolas-raoul** [mrpritchett/buddydrive#49]
[Enhancement]

CMIS is a protocol for document repositories interoperability.
http://en.wikipedia.org/wiki/Content_Management_Interoperability_Services

Implementing it would allow documents to be easily migrated from SharePoint/Alfresco/Nuxeo/Documentum/Lotus/FileNet/etc.

It would also allow to use CmisSync, which means that people would be able to synchronize to their local Windows/Mac/Linux, making it as easy to use as Dropbox, and enabling more complex scenarios (example: coupling with a scanner).
Disclaimer: I make CmisSync. It is open source.

**Comment by imath** [comment]
Hi,

I don't know anything about it, could you pull a request to let me test and see if i can include this in the plugin ?

**Comment by mrpritchett** [comment]
No pull request added. Feature not likely in the scope of the current project.
