### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by slaFFik** [mrpritchett/buddydrive#64]
#### Navigating after searching:
- Go to folder.
- Try to serach anything in it
- Go to `All` tab
- Search term is preserved, not flushed. 
- Search results in All folder are displayed
#### Recursive search

Currently is not supported.
#### Special chars in search

They are searched strangely. 
- `-` is not searched, although present in file names and descriptions.

**Comment by imath** [comment]
Thanks for your feedback.

Navigating after searching: that's also the way the BuddyPress members search directory works, you need to empty the search field to reset it. As the field is containing the search it seems the right behavior to me.

Recursive search. I agree, but that's for a future release :)

'-' as the **first** character inserted in the search field is the character WordPress uses to negate a search. That's the reason why you are not getting the results.

but if you do 'f-' for instance search works as expected.
