### ISSUE TITLE
Allowed file types not applied until settings are saved

### ISSUE THREAD

**Issue by boonebgorges** [mrpritchett/buddydrive#71]
By default, a bunch of the file type checkboxes in the admin are checked. But the file types aren't actually saved until the settings page has been saved at least once (such that `buddydrive_get_allowed_upload_exts()` returns empty). The default/fallback values should be consistent.

Possibly related: https://github.com/buddypress/bp-attachments/issues/23

**Comment by imath** [comment]
Thanks for your feedback. I agree there's a problem here. I'll look at it asap.

**Comment by mrpritchett** [comment]
This seems to be resolved. Closing.
