### ISSUE TITLE
Buddydrive Area Empty

### ISSUE THREAD

**Issue by mytval** [mrpritchett/buddydrive#76]
Hi,

I don’t know why suddently, at frontend, my Buddydrive folder is empty (for profile or groups). In the dashboard I can see the files that I’ve uploaded.
How to access my buddydrive files from FrontEnd (as it used to work at the begining)?

I desactivated the plugin and reactivated it back and it was working again. But without making any changes, It goes blank again.

See for group: [](http://uform.me/wp-content/uploads/2016/11/buddydrive_group_blank.png)
See for profile: [](http://uform.me/wp-content/uploads/2016/11/buddydrive_profile_blank.png)

Please help me!

**Comment by imath** [comment]
I don't see anything! have you tried to attach screencaps? if so it failed.

I've dropped the support for this plugin, you should probably ask on the plugin's support forum on WordPress.org

imath.
http://profiles.wordpress.org/imath/
