### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by nibinnelson007** [mrpritchett/buddydrive#79]
Hi,
    Recently i have added a translation in my BuddyPress site after the translation buddy drive is working and it gives me 404 error page. I have 2 languages in my site default language is English and it does not have a language slug so buddy drive works normally but, another language is Arabic and language slug is ar and buddy drive not working.

In English, language URL looks like this: 
http://localhost/social/members/admin/file-sharing/

and in the arabic same page will be like this : 
http://localhost/social/ar/members/admin/ar/file-sharing/

(Here file-sharing is the buddy drive URL)
As u can see in Arabic language slug is repeating also.

Can anybody help me to solve this problem.
Thanks in advance.

**Comment by mrpritchett** [comment]
I'm not sure editing the slug like that will work. Has it worked with other BuddyPress functionality?
